name: Build & Publish

on:
  push:
    branches:
      - "**"           
      - "!dependabot/**"
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin
      - run: npm install --frozen-lockfile --check-files
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}     
  publishRelease:
    name: Potentially publish release
    runs-on: ubuntu-latest
    needs: build
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - run: sudo chmod +x ./publish-release.sh
      - run: sudo ./publish-release.sh