name: Prepare docker artifact (Production)
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
    - run: yarn install
    - run: yarn run build --if-present
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build docker container
      run: |
        TAG=$(date -u +'%Y%m%dT%H%M%SZ')
        docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }}
        docker build -t docker.pkg.github.com/${{ github.repository }}/wedding-catering:$TAG
        docker push docker.pkg.github.com/${{ github.repository }}/wedding-catering:$TAG
