name: Prepare docker artifact (staging) and deploy new container
on:
  push:
    branches:
      - develop
jobs:
  builddeploy:
    name: Build and deploy artifact
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build Go
      run: |
        cd server
        go get -v -t -d ./...
        go build cmd/platform/main.go
